### ISSUE TITLE
BoutMesh failed to read ShiftAngle from the grid

### ISSUE THREAD

**Issue by wphu** [bendudson/hermes-2#11]
Hello,

1. I compile hermes-2 in BOUT++-v4.3.1, when i run uedge-benchmark case, error happens:
"BoutMesh failed to read ShiftAngle from the grid".
Then I copy grid file "cbm18_dens8.grid_nx68ny64_profiles.nc" from hermes-3, it can run successfully, so I think it is grid problem.

2. the default case has no neutral, I want to try neutral case, so I change the BOUT.inp file: frecycle = 0.8  and type = recycling or diffusion2d, but it can not run. could you upload some cases with neutral?

3. will you focus on hermes-3 in future work? now I can not compile hermes-3.

Thanks very much.

**Comment by bendudson** [comment]
1. Thanks, this is probably an old grid file which didn't contain the shift angle. There is an option to calculate shiftangle from the input, but it's not particularly accurate or recommended. I'll try to fix this.
2. Please try `type = mixed` since this is the one used most, and usually the most robust. You might need to set the neutral density `Nn` to a non-zero value
```
[Nn]
function = 0.01
```
3. For simulations I'm currently using hermes-2, but I'm focussing on developing hermes-3. That should compile with the current `master` branch of BOUT++. It's currently very experimental, not yet suitable for production runs, but has some examples in 2D (drift plane) that it can currently run.

**Comment by wphu** [comment]
The neutral case is OK by following the steps you give. 
The comilation of hermes-3 under BOUT-dev master  still won't pass, I will create an issue under hermes-3.

Thank you very much.
