### ISSUE TITLE
error when running uedge-benchmark case

### ISSUE THREAD

**Issue by wphu** [bendudson/hermes-2#4]
I copy BOUT.inp from hermes-2/uedge-benchmark/case0 to hermes-2/uedge-benchmakr, and 
in hermes-2, run: mpiexec -n 16 ./hermes-2 -d uedge-benchmark

The error info is shown below:

Applying Twist-Shift condition. Interpolation: FFT
terminate called after throwing an instance of 'BoutException'
terminate called after throwing an instance of 'BoutException'
terminate called after throwing an instance of 'BoutException'
terminate called after throwing an instance of 'BoutException'
terminate called after throwing an instance of 'BoutException'
Error encountered during initialisation: ====== Exception thrown ======
ERROR: Twist-shift angle 'ShiftAngle' not found.
====== Back trace ======
 -> BoutMesh::load() on line 89 of 'boutmesh.cxx'
====== Exception path ======

Could you help me? please.

**Comment by bendudson** [comment]
Sorry about this; the input file and boundary conditions need to be updated for this example. I will try to do this today.

**Comment by bendudson** [comment]
I've just updated the code and input file, so this case now runs. Quite a lot of things were changed when moving from BOUT++ 3.1 to BOUT++ 4.2 so the test case is probably not quite right yet. I will keep working on it. Please try it and see. You will need to run the simulation on at least 16 cores, due to the branch cuts in X-point geometry. To plot the comparison run "python plotresults.py" from inside the "case0" directory.

**Comment by bendudson** [comment]
I've just updated the code and input file, so this case now runs. Quite a lot of things were changed when moving from BOUT++ 3.1 to BOUT++ 4.2 so the test case is probably not quite right yet. I will keep working on it. Please try it and see. You will need to run the simulation on at least 16 cores, due to the branch cuts in X-point geometry. To plot the comparison run "python plotresults.py" from inside the "case0" directory.

**Comment by wphu** [comment]
> I've just updated the code and input file, so this case now runs. Quite a lot of things were changed when moving from BOUT++ 3.1 to BOUT++ 4.2 so the test case is probably not quite right yet. I will keep working on it. Please try it and see. You will need to run the simulation on at least 16 cores, due to the branch cuts in X-point geometry. To plot the comparison run "python plotresults.py" from inside the "case0" directory.

Thank you very much. I will try and test.

**Comment by wphu** [comment]
The case runs successfully.
